version: "3.7"

x-mysql: &mysql-default
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: root
    MYSQL_PASSWORD: password
    TZ: "Asia/Tokyo"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec puma -C config/puma.rb
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - /var/tmp
      - sockets:/app/tmp/sockets
      #
      - bundle:/bundle
      - rails_cache:/app/tmp/cache
      - node_modules:/app/node_modules
      #
    tty: true
    depends_on:
      - db
    <<: *mysql-default
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    <<: *mysql-default
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - sockets:/app/tmp/sockets
    depends_on:
      - app

volumes:
  db_data:
  sockets:
  bundle:
  node_modules:
  rails_cache:
